export const SET_APP_INFO = 'app/SET_APP_INFO'
export const SET_APP_HISTORY = 'app/SET_APP_HISTORY'
export const CHANGE_DELETE_APP_NAME = 'app/CHANGE_DELETE_APP_NAME'
export const SET_PUBLISH_INFO = 'app/SET_PUBLISH_INFO'
export const SET_APP_DETAIL_PAGE_LOADING = 'app/SET_APP_DETAIL_PAGE_LOADING'

export const UPLOAD_STATUS_NORMAL = 0
export const UPLOAD_STATUS_ACTIVE = 1
export const UPLOAD_STATUS_SUCCESS = 2
export const UPLOAD_STATUS_ERROR = 3